### ISSUE TITLE
Websocket fragments

### ISSUE THREAD

**Issue by fr4ncidir** [arces-wot/sepatools#10]
Apis in C need websocket packets fragmentation. I think this feature is currently not present in SEPAEngine: can you please confirm that?

Without this support I believe C api won't be able to ask for subscriptions having a SPARQL longer than 40/50 chars. Quite annoying, don't you think?

**Comment by lroffia** [comment]
I am writing the new version of the websocket part. So we should check how to implement fragmentation.
